version: '2.2'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./db_entrypoint/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  # Database Manager
  mongo-express:
    image: mongo-express
    ports:
      - 8099:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    links:
      - mongo
  secret_santa:
    image: ghvinerias/secret-santa
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=${MONGODB_HOST}
      - MONGO_PORT=${MONGODB_PORT}
      - MONGO_DB=${MONGODB_DB}
      - MONGO_USER=${MONGODB_USER}
      - MONGO_PASS=${MONGODB_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - EMAIL_SUBJECT=${EMAIL_SUBJECT}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - mongo
