name: Automatic Docker Image Publish

on:
  push:
    branches:
      - main
jobs:
  build-and-publish-automatic:
    name: Build and Publish Docker Image (Automatic)
    if: |
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'Version')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Version Tag
        run: | 
          VERSION_TAG=$(echo ${{ github.event.head_commit.message }} | grep -oP '(?i)version\s*:?\s*\K\d+(\.\d+)+')
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV 
      - name: Get Tag
        run: echo $VERSION_TAG

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.DOCKERUHUB_SECRET }} | docker login -u ghvinerias --password-stdin

      - name: Build Docker Image
        run: docker build -t ghvinerias/secret-santa:$VERSION_TAG -t ghvinerias/secret-santa:latest .

      - name: Publish Docker Image to GitHub Container Registry
        run: docker push -a ghvinerias/secret-santa